import type { LocalizationResource } from "@clerk/types";

export const kuSorani: any = {
  locale: "ku",
  signUp: {
    start: {
      title: "دروستکردنی هەژمار",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      actionText: "هەژمارەکت هەیە؟",
      actionLink: "چوونەژوورەوە",
    },
    emailLink: {
      title: "پشتڕاستکردنەوەی ئیمەیڵ",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      formTitle: "لینکی پشتڕاستکردنەوە",
      formSubtitle: "لینکی پشتڕاستکردنەوەی نێردراو بە ئیمەیڵەکەت بەکارهێنە",
      resendButton: "لینک نەگەیشتووە؟ دووبارە بنێرە",
      verified: {
        title: "سەرکەوتووانە تۆمار بوو",
      },
      loading: {
        title: "تۆمار دەکرێت...",
      },
      verifiedSwitchTab: {
        title: "ئیمەیڵەکەت پشتڕاستکراوە",
        subtitle: "بگەڕێوە بۆ لاپەڕەی نوێکراوە بۆ بەردەوامبوون",
        subtitleNewTab: "بگەڕێوە بۆ لاپەڕەی پێشوەوە بۆ بەردەوامبوون",
      },
    },
    emailCode: {
      title: "پشتڕاستکردنەوەی ئیمەیڵ",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      formTitle: "کۆدی پشتڕاستکردنەوە",
      formSubtitle: "کۆدی نێردراو بە ئیمەیڵەکەت بنووسە",
      resendButton: "کۆدەکە نەگەیشتووە؟ دووبارە بنێرە",
    },
    phoneCode: {
      title: "پشتڕاستکردنەوەی ژمارەی مۆبایل",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      formTitle: "کۆدی پشتڕاستکردنەوە",
      formSubtitle: "کۆدی نێردراو بە ژمارەی مۆبایلەکەت بنووسە",
      resendButton: "کۆدەکە نەگەیشتووە؟ دووبارە بنێرە",
    },
    restrictedAccess: {
      actionLink: "hemn ",
      actionText: "hemn hemn text",
      blockButton__emailSupport: "hi hih ihihihi",
    },
    username: {
      title: "ناوی بەکارهێنەر",
      subtitle: "ناوی بەکارهێنەرەکەت داخل بکە",
    },
    password: {
      title: "وشەی نهێنی",
      subtitle: "وشەی نهێنییەک دیاری بکە",
    },
    continue: {
      title: "پڕکردنەوەی زانیاریەکانی بەجێماوە",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      actionText: "هەژمارەکت هەیە؟",
      actionLink: "چوونەژوورەوە",
    },
  },

  signIn: {
    start: {
      title: "چوونەژوورەوە",
      subtitle: "بۆ بەردەوامبوون بۆ {{applicationName}}",
      actionText: "هەژمارێک نییە؟",
      actionLink: "دروستکردنی هەژمار",
    },
    password: {
      title: "وشەی نهێنی",
      subtitle: "وشەی نهێنییەکەت بنووسە",
    },
    username: {
      title: "ناوی بەکارهێنەر",
      subtitle: "ناوی بەکارهێنەرەکەت داخل بکە",
    },
    emailCode: {
      title: "پشتڕاستکردنەوەی ئیمەیڵ",
      subtitle: "کۆدی پشتڕاستکردنەوەی نێردراو بە ئیمەیڵەکەت داخل بکە",
      resendButton: "کۆدەکە نەگەیشتووە؟ دووبارە بنێرە",
    },
    phoneCode: {
      title: "پشتڕاستکردنەوەی ژمارەی مۆبایل",
      subtitle: "کۆدی پشتڕاستکردنەوەی نێردراو بە ژمارەی مۆبایلەکەت داخل بکە",
      resendButton: "کۆدەکە نەگەیشتووە؟ دووبارە بنێرە",
    },
  },
};

export const kurdishSoraniLocalization: LocalizationResource = {
  locale: "ckb",
  maintenanceMode: "دۆخی چاککردن",
  roles: {
    "org:teacher": "مامۆستا",
  },
  socialButtonsBlockButton: "بچۆ ژوورەوە لەگەڵ {{provider}}",
  dividerText: "یان",
  formFieldLabel__emailAddress: "ناونیشانی ئیمەیل",
  formFieldLabel__password: "وشەی تێپەڕ",
  formFieldLabel__username: "ناوی بەکارهێنەر",
  formFieldLabel__firstName: "ناوی یەکەم",
  formFieldLabel__lastName: "ناوی کۆتایی",
  formFieldLabel__organizationName: "ناوی ڕێکخراو",
  formFieldLabel__organizationSlug: "سلەگی ڕێکخراو",
  formFieldLabel__organizationDomain: "دۆمەینی ڕێکخراو",
  formFieldLabel__organizationDomainEmailAddress:
    "ناونیشانی ئیمەیلی دۆمەینی ڕێکخراو",
  formFieldLabel__confirmDeletion: "دڵنیابوونەوە لە سڕینەوە",
  formFieldLabel__role: "ڕۆڵ",
  formFieldLabel__passkeyName: "ناوی پاسکی",
  formFieldInputPlaceholder__emailAddress: "ئیمەیلەکەت بنووسە",
  formFieldInputPlaceholder__password: "وشەی تێپەڕ بنووسە",
  formFieldInputPlaceholder__username: "ناوی بەکارهێنەر بنووسە",
  formFieldInputPlaceholder__firstName: "ناوی یەکەم بنووسە",
  formFieldInputPlaceholder__lastName: "ناوی کۆتایی بنووسە",
  formFieldInputPlaceholder__organizationName: "ناوی ڕێکخراو بنووسە",
  formFieldInputPlaceholder__organizationSlug: "سلەگی ڕێکخراو بنووسە",
  formFieldInputPlaceholder__organizationDomain: "دۆمەینی ڕێکخراو بنووسە",
  formFieldInputPlaceholder__organizationDomainEmailAddress:
    "ناونیشانی ئیمەیلی دۆمەینی ڕێکخراو بنووسە",
  formFieldError__notMatchingPasswords: "وشەی تێپەڕەکان جیاوازن",
  formFieldError__matchingPasswords: "وشەی تێپەڕەکان هاوشێوەن",
  formFieldError__verificationLinkExpired:
    "بەستەری پشتڕاستکردنەوە کۆتایی هاتووە",
  formFieldAction__forgotPassword: "وشەی تێپەڕەکەمت لەبیرکردووە؟",
  formFieldHintText__optional: "دڵخوازە",
  formFieldHintText__slug: "سلەگ ناونیشانێکی تایبەتمەندییە بۆ ڕێکخراوەکەت",
  formButtonPrimary: "بڕۆ",
  formButtonPrimary__verify: "پشتڕاستکردنەوە",
  signInEnterPasswordTitle: "وشەی تێپەڕەکەت بنووسە",
  backButton: "گەڕانەوە",
  footerActionLink__useAnotherMethod: "شێوازێکی تر بەکاربهێنە",
  badge__primary: "سەرەکی",
  badge__thisDevice: "ئەم ئامێرە",
  badge__userDevice: "ئامێری بەکارهێنەر",
  badge__otherImpersonatorDevice: "ئامێری دیکەی نیشاندەر",
  badge__default: "بنەڕەتی",
  badge__unverified: "پشتڕاستنەکراوە",
  badge__requiresAction: "پێویستی بە کردارە",
  badge__you: "تۆ",
  footerPageLink__help: "یارمەتی",
  footerPageLink__privacy: "تایبەتمەندی",
  footerPageLink__terms: "مەرجەکان",
  paginationButton__previous: "پێشوو",
  paginationButton__next: "دواتر",
  paginationRowText__displaying: "پیشاندان",
  paginationRowText__of: "لە",
  membershipRole__admin: "ئەدمین",
  membershipRole__basicMember: "ئەندامی سەرەکی",
  membershipRole__guestMember: "ئەندامی میوان",
  signUp: {
    start: {
      title: "هەژمارێکی نوێ دروست بکە",
      subtitle: "بۆ دەستپێکردن، تکایە زانیارییەکانی خۆت بنووسە",
      actionText: "هەژمارت هەیە؟",
      actionLink: "چوونەژوورەوە",
      actionLink__use_phone: "ژمارەی مۆبایل بەکاربهێنە",
      actionLink__use_email: "ئیمەیل بەکاربهێنە",
    },
  },
  signIn: {
    start: {
      title: "چوونەژوورەوە",
      subtitle: "بۆ دەستپێکردن، تکایە زانیارییەکانی خۆت بنووسە",
      actionText: "هەژمارت نییە؟",
      actionLink: "هەژمارێکی نوێ دروست بکە",
      actionLink__use_email: "ئیمەیل بەکاربهێنە",
      actionLink__use_phone: "ژمارەی مۆبایل بەکاربهێنە",
      actionLink__use_username: "ناوی بەکارهێنەر بەکاربهێنە",
      actionLink__use_email_username: "ئیمەیل یان ناوی بەکارهێنەر بەکاربهێنە",
      actionLink__use_passkey: "پاسکی بەکاربهێنە",
    },
  },
  userProfile: {
    mobileButton__menu: "مێنوو",
    formButtonPrimary__continue: "بڕۆ",
    formButtonPrimary__save: "پاشەکەوت بکە",
    formButtonPrimary__finish: "تەواو بکە",
    formButtonPrimary__remove: "سڕینەوە",
    formButtonPrimary__add: "زیاد بکە",
    formButtonReset: "هەڵوەشاندنەوە",
    navbar: {
      title: "پڕۆفایل",
      description: "بەڕێوەبردنی زانیارییەکانی هەژمارەکەت",
      account: "هەژمار",
      security: "ئاسایش",
    },
    start: {
      headerTitle__account: "هەژمار",
      headerTitle__security: "ئاسایش",
      profileSection: {
        title: "پڕۆفایل",
        primaryButton: "نوێکردنەوەی پڕۆفایل",
      },
      usernameSection: {
        title: "ناوی بەکارهێنەر",
        primaryButton__updateUsername: "نوێکردنەوەی ناوی بەکارهێنەر",
        primaryButton__setUsername: "دانانی ناوی بەکارهێنەر",
      },
      emailAddressesSection: {
        title: "ناونیشانی ئیمەیل",
        primaryButton: "زیادکردنی ناونیشانی ئیمەیل",
        detailsAction__primary: "سەرەکی",
        detailsAction__nonPrimary: "ناسەرەکی",
        detailsAction__unverified: "پشتڕاستنەکراوە",
        destructiveAction: "سڕینەوە",
      },
      phoneNumbersSection: {
        title: "ژمارەی مۆبایل",
        primaryButton: "زیادکردنی ژمارەی مۆبایل",
        detailsAction__primary: "سەرەکی",
        detailsAction__nonPrimary: "ناسەرەکی",
        detailsAction__unverified: "پشتڕاستنەکراوە",
        destructiveAction: "سڕینەوە",
      },
      connectedAccountsSection: {
        title: "هەژمارە پەیوەندیدارەکان",
        primaryButton: "زیادکردنی هەژمارە پەیوەندیدارەکان",
        actionLabel__connectionFailed: "پەیوەندی شکستی هێنا",
        subtitle__disconnected: "پەیوەندی پچڕاوە",
        destructiveActionTitle: "سڕینەوە",
      },
      passwordSection: {
        title: "وشەی تێپەڕ",
        primaryButton__updatePassword: "نوێکردنەوەی وشەی تێپەڕ",
        primaryButton__setPassword: "دانانی وشەی تێپەڕ",
      },
      passkeysSection: {
        title: "پاسکی",
        menuAction__rename: "گۆڕینی ناو",
        menuAction__destructive: "سڕینەوە",
      },
      mfaSection: {
        title: "دوو هەنگاوە",
        primaryButton: "زیادکردنی دوو هەنگاوە",
        phoneCode: {
          destructiveActionLabel: "سڕینەوە",
          actionLabel__setDefault: "دانانی وەک پێشگریمان",
        },
        backupCodes: {
          headerTitle: "کۆدی پشتیوانی",
          title__regenerate: "دووبارە دروستکردنەوەی کۆدی پشتیوانی",
          subtitle__regenerate: "دووبارە دروستکردنەوەی کۆدی پشتیوانی",
          actionLabel__regenerate: "دووبارە دروستکردنەوە",
        },
        totp: {
          headerTitle: "کۆدی دوو هەنگاوە",
          destructiveActionTitle: "سڕینەوە",
        },
      },
      activeDevicesSection: {
        title: "ئامێرە چالاکەکان",
        destructiveAction: "سڕینەوە",
      },
      web3WalletsSection: {
        title: "جەڵتەی وێب ٣",
        primaryButton: "زیادکردنی جەڵتەی وێب ٣",
        destructiveAction: "سڕینەوە",
      },
      dangerSection: {
        title: "مەترسی",
        deleteAccountButton: "سڕینەوەی هەژمار",
      },
    },
    profilePage: {
      title: "پڕۆفایل",
      imageFormTitle: "وێنەی پڕۆفایل",
      imageFormSubtitle: "وێنەی پڕۆفایل بار بکە",
      imageFormDestructiveActionSubtitle: "سڕینەوەی وێنەی پڕۆفایل",
      fileDropAreaHint: "وێنەی پڕۆفایل بار بکە",
      readonly: "تەنیا خوێندنەوە",
      successMessage: "پڕۆفایلەکەت بە سەرکەوتوویی نوێکرایەوە",
    },
    usernamePage: {
      successMessage: "ناوی بەکارهێنەرەکەت بە سەرکەوتوویی نوێکرایەوە",
      title__set: "دانانی ناوی بەکارهێنەر",
      title__update: "نوێکردنەوەی ناوی بەکارهێنەر",
    },
    emailAddressPage: {
      title: "ناونیشانی ئیمەیل",
      verifyTitle: "پشتڕاستکردنەوەی ناونیشانی ئیمەیل",
      emailCode: {
        formTitle: "کۆدی پۆستی ئەلیکترۆنی",
        formSubtitle: "کۆدی ناردنەوەی ناونیشانی ئیمەیل",
        resendButton: "دووبارە ناردنەوە",
        successMessage: "ناونیشانی ئیمەیلەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      },
      emailLink: {
        formTitle: "بەستەری پۆستی ئەلیکترۆنی",
        formSubtitle: "بەستەری ناردنەوەی ناونیشانی ئیمەیل",
        resendButton: "دووبارە ناردنەوە",
        successMessage: "ناونیشانی ئیمەیلەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      },
      removeResource: {
        title: "سڕینەوەی ناونیشانی ئیمەیل",
        messageLine1: "دڵنیای لە سڕینەوەی ناونیشانی ئیمەیل؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "ناونیشانی ئیمەیلەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    passkeyScreen: {
      title__rename: "گۆڕینی ناوی پاسکی",
      subtitle__rename: "گۆڕینی ناوی پاسکی",
      removeResource: {
        title: "سڕینەوەی پاسکی",
        messageLine1: "دڵنیای لە سڕینەوەی پاسکی؟",
      },
    },
    phoneNumberPage: {
      title: "ژمارەی مۆبایل",
      verifyTitle: "پشتڕاستکردنەوەی ژمارەی مۆبایل",
      verifySubtitle: "ژمارەی مۆبایل بنووسە",
      successMessage: "ژمارەی مۆبایلەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      infoText: "ژمارەی مۆبایل بنووسە",
      removeResource: {
        title: "سڕینەوەی ژمارەی مۆبایل",
        messageLine1: "دڵنیای لە سڕینەوەی ژمارەی مۆبایل؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "ژمارەی مۆبایلەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    connectedAccountPage: {
      title: "هەژمارە پەیوەندیدارەکان",
      formHint: "هەژمارە پەیوەندیدارەکان زیاد بکە",
      formHint__noAccounts: "هیچ هەژمارێکی پەیوەندیدار نییە",
      socialButtonsBlockButton: "پەیوەندی بکە بە {{provider}}",
      successMessage: "هەژمارە پەیوەندیدارەکەت بە سەرکەوتوویی زیادکرا",
      removeResource: {
        title: "سڕینەوەی هەژمارە پەیوەندیدارەکان",
        messageLine1: "دڵنیای لە سڕینەوەی هەژمارە پەیوەندیدارەکان؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "هەژمارە پەیوەندیدارەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    web3WalletPage: {
      title: "جەڵتەی وێب ٣",
      subtitle__availableWallets: "جەڵتەی وێب ٣ زیاد بکە",
      subtitle__unavailableWallets: "هیچ جەڵتەیەکی وێب ٣ بەردەست نییە",
      web3WalletButtonsBlockButton: "جەڵتەی وێب ٣ زیاد بکە",
      successMessage: "جەڵتەی وێب ٣ەکەت بە سەرکەوتوویی زیادکرا",
      removeResource: {
        title: "سڕینەوەی جەڵتەی وێب ٣",
        messageLine1: "دڵنیای لە سڕینەوەی جەڵتەی وێب ٣؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "جەڵتەی وێب ٣ەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    passwordPage: {
      successMessage__set: "وشەی تێپەڕەکەت بە سەرکەوتوویی دانرا",
      successMessage__update: "وشەی تێپەڕەکەت بە سەرکەوتوویی نوێکرایەوە",
      successMessage__signOutOfOtherSessions: "دەرچوون لە هەموو ئامێرەکانی تر",
      checkboxInfoText__signOutOfOtherSessions:
        "دەرچوون لە هەموو ئامێرەکانی تر",
      readonly: "تەنیا خوێندنەوە",
      title__set: "دانانی وشەی تێپەڕ",
      title__update: "نوێکردنەوەی وشەی تێپەڕ",
    },
    mfaPage: {
      title: "دوو هەنگاوە",
      formHint: "دوو هەنگاوە زیاد بکە",
    },
    mfaTOTPPage: {
      title: "کۆدی دوو هەنگاوە",
      verifyTitle: "پشتڕاستکردنەوەی کۆدی دوو هەنگاوە",
      verifySubtitle: "کۆدی دوو هەنگاوە بنووسە",
      successMessage: "کۆدی دوو هەنگاوەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      authenticatorApp: {
        infoText__ableToScan: "دەتوانیت کۆدەکە بخوێنیتەوە",
        infoText__unableToScan: "ناتوانیت کۆدەکە بخوێنیتەوە",
        inputLabel__unableToScan1: "کۆدەکە بنووسە",
        inputLabel__unableToScan2: "کۆدەکە بنووسە",
        buttonAbleToScan__nonPrimary: "دەتوانیت کۆدەکە بخوێنیتەوە",
        buttonUnableToScan__nonPrimary: "ناتوانیت کۆدەکە بخوێنیتەوە",
      },
      removeResource: {
        title: "سڕینەوەی کۆدی دوو هەنگاوە",
        messageLine1: "دڵنیای لە سڕینەوەی کۆدی دوو هەنگاوە؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "کۆدی دوو هەنگاوەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    mfaPhoneCodePage: {
      title: "کۆدی ژمارەی مۆبایل",
      primaryButton__addPhoneNumber: "ژمارەی مۆبایل زیاد بکە",
      backButton: "گەڕانەوە",
      subtitle__availablePhoneNumbers: "ژمارەی مۆبایل زیاد بکە",
      subtitle__unavailablePhoneNumbers: "هیچ ژمارەیەکی مۆبایل بەردەست نییە",
      successTitle: "کۆدی ژمارەی مۆبایلەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      successMessage1: "کۆدی ژمارەی مۆبایلەکەت بە سەرکەوتوویی پشتڕاستکرایەوە",
      successMessage2: "دەتوانیت دووبارە زیاد بکەیتەوە",
      removeResource: {
        title: "سڕینەوەی کۆدی ژمارەی مۆبایل",
        messageLine1: "دڵنیای لە سڕینەوەی کۆدی ژمارەی مۆبایل؟",
        messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
        successMessage: "کۆدی ژمارەی مۆبایلەکەت بە سەرکەوتوویی سڕایەوە",
      },
    },
    backupCodePage: {
      title: "کۆدی پشتیوانی",
      title__codelist: "کۆدی پشتیوانی",
      subtitle__codelist: "کۆدی پشتیوانی زیاد بکە",
      infoText1: "کۆدی پشتیوانی زیاد بکە",
      infoText2: "دەتوانیت دووبارە زیاد بکەیتەوە",
      successSubtitle: "کۆدی پشتیوانی زیادکرا",
      successMessage: "کۆدی پشتیوانیەکەت بە سەرکەوتوویی زیادکرا",
      actionLabel__copy: "کۆپی بکە",
      actionLabel__copied: "کۆپی کراوە",
      actionLabel__download: "داگرتن",
      actionLabel__print: "چاپکردن",
    },
    deletePage: {
      title: "سڕینەوەی هەژمار",
      messageLine1: "دڵنیای لە سڕینەوەی هەژمارەکەت؟",
      messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
      actionDescription: "دڵنیابوونەوە لە سڕینەوە",
      confirm: "سڕینەوە",
    },
  },
  userButton: {
    action__manageAccount: "بەڕێوەبردنی هەژمار",
    action__signOut: "دەرچوون",
    action__signOutAll: "دەرچوون لە هەموو ئامێرەکان",
    action__addAccount: "زیادکردنی هەژمار",
  },
  organizationSwitcher: {
    personalWorkspace: "کارگەی کەسی",
    notSelected: "هیچ هەڵبژاردنێک نەکراوە",
    action__createOrganization: "دروستکردنی ڕێکخراو",
    action__manageOrganization: "بەڕێوەبردنی ڕێکخراو",
    action__invitationAccept: "قبوڵکردنی بانگهێشت",
    action__suggestionsAccept: "قبوڵکردنی پێشنیارەکان",
    suggestionsAcceptedLabel: "پێشنیارەکان قبوڵکران",
  },
  impersonationFab: {
    title: "نیشاندەر",
    action__signOut: "دەرچوون",
  },
  organizationProfile: {
    navbar: {
      title: "ڕێکخراو",
      description: "بەڕێوەبردنی زانیارییەکانی ڕێکخراوەکەت",
      general: "گشتی",
      members: "ئەندامان",
    },
    badge__unverified: "پشتڕاستنەکراوە",
    badge__automaticInvitation: "بانگهێشتکردنی ئۆتۆماتیکی",
    badge__automaticSuggestion: "پێشنیاری ئۆتۆماتیکی",
    badge__manualInvitation: "بانگهێشتکردنی دەستی",
    start: {
      headerTitle__members: "ئەندامان",
      headerTitle__general: "گشتی",
      profileSection: {
        title: "پڕۆفایل",
        primaryButton: "نوێکردنەوەی پڕۆفایل",
        uploadAction__title: "بارکردنی وێنەی پڕۆفایل",
      },
    },
    profilePage: {
      title: "پڕۆفایل",
      successMessage: "پڕۆفایلەکەت بە سەرکەوتوویی نوێکرایەوە",
      dangerSection: {
        title: "مەترسی",
        leaveOrganization: {
          title: "دەرچوون لە ڕێکخراو",
          messageLine1: "دڵنیای لە دەرچوون لە ڕێکخراو؟",
          messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
          successMessage: "دەرچوون لە ڕێکخراو بە سەرکەوتوویی",
          actionDescription: "دڵنیابوونەوە لە دەرچوون",
        },
        deleteOrganization: {
          title: "سڕینەوەی ڕێکخراو",
          messageLine1: "دڵنیای لە سڕینەوەی ڕێکخراو؟",
          messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
          actionDescription: "دڵنیابوونەوە لە سڕینەوە",
          successMessage: "ڕێکخراوەکەت بە سەرکەوتوویی سڕایەوە",
        },
      },
      domainSection: {
        title: "دۆمەین",
        subtitle: "بەڕێوەبردنی دۆمەینەکان",
        primaryButton: "زیادکردنی دۆمەین",
        menuAction__verify: "پشتڕاستکردنەوە",
        menuAction__remove: "سڕینەوە",
        menuAction__manage: "بەڕێوەبردن",
      },
    },
    createDomainPage: {
      title: "دروستکردنی دۆمەین",
      subtitle: "دروستکردنی دۆمەینی نوێ",
    },
    verifyDomainPage: {
      title: "پشتڕاستکردنەوەی دۆمەین",
      subtitle: "پشتڕاستکردنەوەی دۆمەین",
      subtitleVerificationCodeScreen: "کۆدی پشتڕاستکردنەوە بنووسە",
      formTitle: "کۆدی پشتڕاستکردنەوە",
      formSubtitle: "کۆدی پشتڕاستکردنەوە بنووسە",
      resendButton: "دووبارە ناردنەوە",
    },
    verifiedDomainPage: {
      title: "دۆمەینی پشتڕاستکراو",
      subtitle: "دۆمەینی پشتڕاستکراو",
      start: {
        headerTitle__enrollment: "تۆمارکردن",
        headerTitle__danger: "مەترسی",
      },
      enrollmentTab: {
        subtitle: "تۆمارکردنی ئەندامان",
        manualInvitationOption__label: "بانگهێشتکردنی دەستی",
        manualInvitationOption__description: "بانگهێشتکردنی دەستی بۆ ئەندامان",
        automaticInvitationOption__label: "بانگهێشتکردنی ئۆتۆماتیکی",
        automaticInvitationOption__description: "بانگهێشتکردنی ئۆتۆماتیکی بۆ ئەندامان",
        automaticSuggestionOption__label: "پێشنیاری ئۆتۆماتیکی",
        automaticSuggestionOption__description: "پێشنیاری ئۆتۆماتیکی بۆ ئەندامان",
        calloutInfoLabel: "زانیاری",
        calloutInvitationCountLabel: "ژمارەی بانگهێشتەکان",
        calloutSuggestionCountLabel: "ژمارەی پێشنیارەکان",
      },
      dangerTab: {
        removeDomainTitle: "سڕینەوەی دۆمەین",
        removeDomainSubtitle: "سڕینەوەی دۆمەین",
        removeDomainActionLabel__remove: "سڕینەوە",
        calloutInfoLabel: "زانیاری",
      },
    },
    invitePage: {
      title: "بانگهێشتکردن",
      subtitle: "بانگهێشتکردنی ئەندامان",
      successMessage: "بانگهێشتەکەت بە سەرکەوتوویی نێردرا",
      detailsTitle__inviteFailed: "بانگهێشتکردن شکستی هێنا",
      formButtonPrimary__continue: "بەردەوام بە",
      selectDropdown__role: "ڕۆڵ",
    },
    removeDomainPage: {
      title: "سڕینەوەی دۆمەین",
      messageLine1: "دڵنیای لە سڕینەوەی دۆمەین؟",
      messageLine2: "دەتوانیت دووبارە زیاد بکەیتەوە",
      successMessage: "دۆمەینەکەت بە سەرکەوتوویی سڕایەوە",
    },
    membersPage: {
      detailsTitle__emptyRow: "هیچ ئەندامێک نییە",
      action__invite: "بانگهێشتکردن",
      start: {
        headerTitle__members: "ئەندامان",
        headerTitle__invitations: "بانگهێشتەکان",
        headerTitle__requests: "داواکاریەکان",
      },
      activeMembersTab: {
        tableHeader__user: "بەکارهێنەر",
        tableHeader__joined: "بەشداری کرد",
        tableHeader__role: "ڕۆڵ",
        tableHeader__actions: "کردارەکان",
        menuAction__remove: "سڕینەوە",
      },
      invitedMembersTab: {
        tableHeader__invited: "بانگهێشتکراو",
        menuAction__revoke: "هەڵوەشاندنەوە",
      },
      invitationsTab: {
        table__emptyRow: "هیچ بانگهێشتێک نییە",
        autoInvitations: {
          headerTitle: "بانگهێشتە ئۆتۆماتیکیەکان",
          headerSubtitle: "بانگهێشتە ئۆتۆماتیکیەکان",
          primaryButton: "بانگهێشتکردن",
        },
      },
      requestsTab: {
        tableHeader__requested: "داواکراو",
        menuAction__approve: "پەسەندکردن",
        menuAction__reject: "ڕەتکردنەوە",
        table__emptyRow: "هیچ داواکاریێک نییە",
        autoSuggestions: {
          headerTitle: "پێشنیارە ئۆتۆماتیکیەکان",
          headerSubtitle: "پێشنیارە ئۆتۆماتیکیەکان",
          primaryButton: "پێشنیارکردن",
        },
      },
    },
  },
  createOrganization: {
    title: "دروستکردنی ڕێکخراو",
    formButtonSubmit: "دروستکردن",
    invitePage: {
      formButtonReset: "هەڵوەشاندنەوە",
    },
  },
  organizationList: {
    createOrganization: "دروستکردنی ڕێکخراو",
    title: "ڕێکخراوەکان",
    titleWithoutPersonal: "ڕێکخراوەکان",
    subtitle: "بەڕێوەبردنی ڕێکخراوەکان",
    action__invitationAccept: "قبوڵکردنی بانگهێشت",
    invitationAcceptedLabel: "بانگهێشتەکان قبوڵکران",
    action__suggestionsAccept: "قبوڵکردنی پێشنیارەکان",
    suggestionsAcceptedLabel: "پێشنیارەکان قبوڵکران",
    action__createOrganization: "دروستکردنی ڕێکخراو",
  },
  unstable__errors: {},
  dates: {
    previous6Days: "٦ ڕۆژی پێشوو",
    lastDay: "دوایین ڕۆژ",
    sameDay: "هەمان ڕۆژ",
    nextDay: "ڕۆژی دواتر",
    next6Days: "٦ ڕۆژی دواتر",
    numeric: "ژمارەیی",
  },
};
